---
- name: configure postgres master node
  become: true
  become_user: root
  hosts: db_master
  roles:
    - role: postgresql
      vars:
        postgresql_role: master

- name: configure postgres replica node
  become: true
  become_user: root
  hosts: db_replica
  roles:
    - role: postgresql
      vars:
        postgresql_role: replica
