---
# tasks file for postgresql
- name: Allow access to tcp port 5432
  ufw:
    rule: allow
    port: 5432
    proto: tcp
    
- name: PostgreSQL | Install packages
  become: yes
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present
    update_cache: true

- name: PostgreSQL | Check if PostgreSQL is initialized
  become: yes
  stat:
    path: "{{ postgresql_conf_dir }}/pg_hba.conf"
  register: postgres_data

- name: PostgreSQL | Create the postgresql data directory if it is not in the default place
  become: yes
  file: 
    dest: "{{ postgresql_custom_data_dir }}"
    owner: postgres
    group: postgres
    mode: "0700"
    recurse: yes
    state: directory
  when: postgresql_custom_data_dir is defined

- name: PostgreSQL | Set the postgresql data dir if it is different from the default
  become: yes
  lineinfile: 
    path: "{{ postgresql_conf_dir }}/postgresql.conf"
    regexp: "^(.*)data_directory(.*)$"
    line: "data_directory = '{{ postgresql_custom_data_dir }}/main'"
    backrefs: yes
  when: postgresql_custom_data_dir is defined

- name: PostgreSQL | Copy the postgresql data directory into the new place
  become: yes
  copy:
    src: "{{ postgresql_data_dir }}"
    dest: "{{ postgresql_custom_data_dir }}"
    owner: postgres
    group: postgres
    remote_src: true
  when: postgresql_custom_data_dir is defined

- name: PostgreSQL | start postgres
  become: yes
  systemd:
    name: postgresql
    state: started
    enabled: yes

- include_tasks: "{{ postgresql_role }}.yml"
  when: postgresql_role != "skip"