- include_tasks: "install.yml"
- include_tasks: "custom-dir.yml"

- name: PostgreSQL - copy data to custom dir
  become: yes
  synchronize:
    src: "{{ postgresql_data_dir }}"
    dest: "{{ postgresql_custom_data_dir }}"
  delegate_to: "{{ inventory_hostname }}"  
  when: postgresql_custom_data_dir is defined
  tags:
    - molecule-idempotence-notest

- name: PostgreSQL - configure master
  become: yes
  blockinfile:
    path: "{{ postgresql_conf_dir }}/postgresql.conf"
    create: yes
    block: |
      listen_addresses = '*'
      wal_level = hot_standby
      archive_mode = on
      archive_command = 'cd .'
      max_wal_senders = 8
      hot_standby = on

- name: PostgreSQL - add trust in pg_hba.conf
  become: true
  lineinfile:
    state: present
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    regexp: 'host.*replication.*{{ item }}/32.*trust'
    line: 'host    replication    {{ postgresql_replica_user }}  {{ item }}/32 trust'
  loop: "{{ postgresql_replica_address }}"
  when: postgresql_replica_address is defined

- name: PostgreSQL - restart
  systemd:
    name: postgresql@12-main
    state: restarted
  become: true

- include_tasks: "users-and-databases.yml"
- include_tasks: "replica-user.yml"