
- include_tasks: "install.yml"
- include_tasks: "clean-dir.yml"
- include_tasks: "custom-dir.yml"

- name: PostgreSQL - configure replica
  become: yes
  blockinfile:
    path: "{{ postgresql_conf_dir }}/postgresql.conf"
    create: yes
    block: |
      listen_addresses = '*'
      wal_level = hot_standby
      archive_mode = on
      archive_command = 'cd .'
      max_wal_senders = 8
      hot_standby = on
    
- name: PostgreSQL - add trust for master in pg_hba.conf
  become: yes
  lineinfile:
    state: present
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    regexp: 'host.*replication.*{{ postgresql_master_address }}/32.*trust'
    line: 'host    replication    postgres    {{ postgresql_master_address }}/32 trust'
  when: postgresql_master_address is defined

- name: PostgreSQL - init replica
  become: yes
  become_user: postgres
  shell: "pg_basebackup -D {{ postgresql_custom_data_dir | default(postgresql_data_dir) }} -h {{ postgresql_master_address }} -X stream -c fast -U {{ postgresql_replica_user }} -w -R"
  notify: restart postgres
  tags:
    - molecule-idempotence-notest
