- name: PostgreSQL | Configure replica server
  become: yes
  blockinfile:
    path: "{{ postgresql_conf_dir }}/postgresql.conf"
    create: yes
    block: |
      listen_addresses = '*'
      wal_level = hot_standby
      archive_mode = on
      archive_command = 'cd .'
      max_wal_senders = 8
      hot_standby = on
  notify: restart postgres

- name: PostgreSQL | Install acl
  become: yes
  apt:
    name:
      - acl
    state: present
    update_cache: true
    
- name: PostgreSQL | Grant postgres
  shell: "sudo usermod -a -G sudo postgres"

- name: PostgreSQL | Add trust for master in pg_hba.conf
  become: yes
  lineinfile:
    state: present
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    regexp: 'host.*replication.*{{ postgresql_master_address }}/32.*trust'
    line: 'host    replication    postgres    {{ postgresql_master_address }}/32 trust'
  when: postgresql_master_address is defined

- name: PostgreSQL | Stop PostgreSQL
  become: yes
  service:
    name: postgresql
    state: stopped

- name: PostgreSQL | Clear out data directory
  become: yes
  file:
    path: "{{ postgresql_custom_data_dir | default(postgresql_data_dir) }}"
    state: absent

- name: PostgreSQL | Create empty data directory
  become: yes  
  file:
    path: "{{ postgresql_data_dir}}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: PostgreSQL | Initialize the slave database
  become: yes
  shell: "pg_basebackup -D {{ postgresql_custom_data_dir | default(postgresql_data_dir) }} -h {{ postgresql_master_address }} -X stream -c fast -U {{ postgresql_replica_user }} -w -R"

- name: PostgreSQL | Recursively change ownership
  become: yes
  shell: "chown -R postgres {{  postgresql_custom_data_dir | default(postgresql_data_dir) }} "
  notify: restart postgres
