---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
  default_box: 'ubuntu/focal64'

platforms:
  - name: db_master
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      synced_folder: true
    box: 'ubuntu/focal64'
    memory: 512
    cpus: 1

  - name: db_replica
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      synced_folder: true
    box: 'ubuntu/focal64'
    memory: 512
    cpus: 1
      

provisioner:
  name: ansible
  inventory:
    links:
      hosts: /cygdrive/c/Users/ivano/vagrant-test/inventory/hosts
      group_vars: /cygdrive/c/Users/ivano/vagrant-test/inventory/group_vars
      host_vars: /cygdrive/c/Users/ivano/vagrant-test/inventory/host_vars

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
